rcbops/molecule-rpc-openstack-post-deploy

molecule/default/tests/test_hypervisor_free.py

This commit implements the `rpc-hypervisor-free` check from the
[pccommon.sh](https://github.com/rsoprivatecloud/openstack-ops/blob/master/playbooks/files/rpc-o-support/pccommon.sh)
script.

ASC-157 add hypervisor allocation test

---

molecule/default/tests/test_dhcp_agents.py

This commit adds a test to ensure that the OpenStack DHCP agents are UP
for all OpenStack networks.

ASC-157 Add DHCP agents test

---

molecule/default/playbook.yml
molecule/default/tests/test_mysql_replication.py

This commit adds a test to ensure that mysql replication has 2 active
slaves running.

ASC-157 Add MySQL replication test

---

molecule/default/playbook.yml
molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_hypervisor_free.py

This PR is to refactor existing tests to `lxc-attach` to the utility container in order to execute `openstack` cli commands. It also switches the format of the output of these commands to JSON in order to simplify the processing of the command results.

ASC-157 Use lxc-attach for openstack commands

---

molecule/default/playbook.yml
molecule/default/tests/test_bridges.py
molecule/default/tests/test_dead_taps.py
tasks/main.yml

This commit adds a test to ensure that no "dead taps" are present
on the deployment host.

ASC-157 Add dead tap test

---

molecule/default/tests/test_hypervisor_free.py

This commit fixes a bug in the `test_hypervisor_free.py` test.
Previously, the ratios were not set to use the global ratios in the
`test_hypervisor_free` test. This commit adds the global declarations in
the context of that test and ensures that they have a seed value set in
global namespace.

ASC-157 Fix free ratio globals

---

molecule/default/tests/test_env_scan.py

The `placement` user is not present on a `newton` deployment. This
commit removes the check for this user.

ASC-572 Remove check for placement user

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py
tasks/main.yml
tasks/support_key.yml
vars/main.yml

This commit implements the `rpc-instance-per-network-per-hypervisor`
test from openstack-ops `pccommon.sh` script. It validates that a server
instance per network, per hypervisor has proper external network connectivity.

ASC-241 - Test instance per net per hypervisor

---

molecule/default/create.yml

This commit fixes a syntax error in the molecule create playbook. This
error was introduced by the default molecule cookie cutter template.

MAINT - Fix syntax error in molecule create

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py

This commit skips the instance_per_network_per_hypervisor.py test.
Currently, this test fails on newton and newton-rc installations due to
the `openstack image list` command not returning any Ubuntu images.
Further research is required to determine the root cause of this failure
and to fix it. This work has been captured in ASC-639.

ASC-572 Skip instance_per_network_per_hypervisor

---

tasks/main.yml

This commit prioritizes openvswitch installation in order to ensure it
is not skipped if there is a failure in additional tasks. This
prioritization is done specifically so that the `test_dead_taps.py`
test will execute atomically from other test requirements.

ASC-636 Prioritize openvswitch install

---

molecule/default/playbook.yml
tasks/support_key.yml

This commit updates the role tasks to add the ssh key to nova using the
utility container. The previous venv deployed to the network host does
not add any value and is eliminated. Application of the tasks has also
been throttled to just the first matching host is the network_hosts
group.

ASC-636 Deploy key pair to nova on utility

---

molecule/default/tests/test_for_acs-150.py
molecule/default/tests/test_rpc_version.py

This commit adds tests to validate the expected versions of OSA and RPC
were installed.
This implements manual test number 5 on the
[Post-Deploy QC Process document](https://one.rackspace.com/pages/viewpage.action?pageId=110992052)

ASC-324 Add tests for OSA and RPC versions

---

molecule/default/tests/test_rpc_version.py

This commit fixes an incorrect method call to a pytest-rpc helper.

ASC-234 Fix helper call

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py
tasks/flavor_setup.yml
tasks/image_setup.yml
tasks/main.yml
tasks/network_setup.yml
tasks/security_group_setup.yml
tasks/server_setup.yml
tasks/support_key.yml
tasks/volume_setup.yml
vars/main.yml

This PR updates the instance_per_network_per_hypervisor test to use
the resources created during the converge step rather than the
'fixtures' that were previously defined.

ASC-241 use converged resources in test

---

tasks/main.yml
tasks/server_delete.yml
tasks/server_setup.yml

This commit fixes a logical error in the ordering of the ansible
OpenStack setup operations. This change ensures that all servers are
deleted prior to the network setup. This frees the network from any IP
bindings prior to delete/create. The network setup then happens prior to
server creation ensuring that the test network is available to bind to
prior to server creation.

ASC-241 Delete servers before network setup

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py
tasks/support_key.yml

This commit adds logic to the test_instance_per_network_per_hypervisor
test to connect to a neutron-agent whether it has been deployed as a
container or a baremetal host. Prior to this commit it was assumed that
neutron-agent hosts were containers.

ASC-241 Connect neutron-agent container/baremetal

---

tasks/network_setup.yml

This commit corrects the incorrect `--shared` network create argument to
`--share`.

ASC-241 Fix network create share argument

---

molecule/default/tests/test_for_acs-295.py
molecule/default/tests/test_swift_ring_data_balance.py

This commit adds tests for validating that the three swift rings (account,
container, object) have partition values greater than zero and balance
values less than one.
This test covers 24a in the RPC 10 + Post-Deployment QC process.

ASC-296 Verify swift ring data and balance

---

molecule/default/tests/test_for_acs-295.py

This commit deletes the "swift full rebalanced" test.
This test is seems like a mitigation step to perform if the previous
balance test does not result in balance values of less than 1.0. It is not
practical to wait 'a few hours' when running automated tests to validate that
the balance has reached a 0.00 value across all devices.

ASC-297 Delete swift fully rebalanced test

---

molecule/default/tests/test_for_acs-150.py

This commit deletes the test stub for the verify ansible playbooks test.
As indicated in the test description in the *RPC 10 + Post-Deployment QC
process* document, this action should not be taken on releases >= liberty.
Since we are not testing releases older than newton, this validation is not
applicable.

ASC-264 Delete verify ansible playbook test

---

molecule/default/tests/test_for_acs-150.py

This commit deletes the test stub for the "Verify Kibana and Horizon are
accessible without SSH tunneling" test.
The purpose of this validation is to ensure that a customer deployment
is accessible via the rackspace bastion socks proxy. Since CI
deployments do not occur on a private external network, such a
validation cannot be properly executed in the CI gating jobs. Therefore,
this test is being removed from the suite.

ASC-266 Delete socks proxy access test

---

molecule/default/tests/test_for_acs-295.py
molecule/default/tests/test_swift_dispersion.py

This commit adds the implementation for the `verify_dispersion_populate`
and `verify_dispersion_report` to run the `swift-dispersion-populate`
and `swift-dispersion-report` commands and ensure that they complete
without error. This test is 24.e. in the *RPC 10+ Post Deployment QC*
document.

ASC-300 Implement swift-dispersion tests

---

molecule/default/tests/test_for_acs-150.py

Per asc team's decision, we are not going to do ui testing at this time, so the test case of verifying instance's console in Horizon should be deleted from the list of planned tests

(ASC-265) delete UI test case view instance console

---

tasks/security_group_setup.yml

This commit removes the `--external-ip` flag from the security group
rule create commands in the converge tasks. This flag is not available
in the newton version of the openstack cli command and was causing the
execution of this task to fail. Because the flag was being set to its
default value, not having it in newer openstack deploys will not have
any effect on its execution.

ASC-790 Remove external-ip in security group rule

---

molecule/default/tests/test_rpc_version.py

This commit updates the `openstack_release_version` test to simply
verify that the `DISTRIB_RELEASE` entry is defined and is set to an
alphanumeric value in the case that the explicit major release version
is not defined by the helper.

ASC-792 No explicit DISTRIB_RELEASE if not defined

---

molecule/default/tests/test_dhcp_agents.py

This commit changes the assert syntax from 'a is b' to 'a == b'. Prior
to this commit, the test failed in CI with the following error:
>                   assert agent['State'] is 'UP'
E                   AssertionError: assert 'UP' is 'UP'

ASC-791 Assert equal for dhcp agent validation

---

molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_rpc_version.py

This commit implements a local version of the `get_osa_version` in order
to determine the expected version values to query for. The helper in
pytest-rpc currently derives these values based on the branch of the
repo in which the executed test resides. However, the molecule tests are
submodules of the rpc-openstack-system-tests repo when executed in CI.
This means that all of the molecule tests are in a detached HEAD state
and cannot determine the properly expected branch.
This implementation assumes that the environment variable for
RE_JOB_BRANCH has been set to the desired value. An exception will be
thrown if the this variable is unset.
The tests that utilize this functionality have been updated to use the
local method.

ASC-791 Add local helper for get_osa_version

---

molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_rpc_version.py

This commit get the value of RPC_PRODUCT_RELEASE to be fed to the
get_osa_version helper to look up the expected values.

ASC-791 Use RPC_PRODUCT_RELEASE for version lookup

---

molecule/default/tests/test_rpc_version.py

This `test_rpc_version` test fails and has been ticketed as RI-410. This
commit skips the test to allow the issue to be resolved without causing
CI runs to remain red.

MAINT - Skip test_rpc_version for RI-410

---

molecule/default/tests/test_rpc_version.py

This commit updates the `test_openstack_codename` test to apply a
regular expression pattern matching any word character if the
`expected_codename` has not been set to a specific value.

MAINT - Fix rpc_version codename regex

---

tasks/main.yml
tasks/network_setup.yml

This commit looks up the `rpc_product_release` fact. It provides
conditional logic to use the legacy `neutron router-gateway-[set|clear]`
when the product version is "newton", otherwise it will use the
`openstack router [set|unset] --external-gateway` command.

ASC-790 Support router-gateway for newton

---

tasks/main.yml
tasks/network_setup.yml

This PR updates the logic for setting the `rpc_product_release`
fact. If the fact is not available from a local fact file, then the
value is assumed to be set via the RPC_PRODUCT_RELEASE environment
variable.

ASC-790 rpc_product_release via ENV if fact unavai

---

constraints.txt
molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_rpc_version.py

This commit updates tests using the `get_osa_version` helper to use the
pytest_rpc version in v0.12.0.

ASC-857 Use pytest_rpc v0.12.0 get_osa_version

---

tasks/os_service_setup.yml

CI failed to create virtual environment on master, looks like it tries to use old pip 8.1.1 to manage the package.
This PR to avoid that by using ansible pip module

(ASC-896) Fix CI failure

---

tasks/os_service_setup.yml

Previous commit (131621ccc2d73d3c230914b489dff58b219bd343) has helped to create virtualenv on SUT, however, it didn't install pip which is need the the next ansible task in os_service_setup.yml.
This PR will try to use the available pip on the host.

(ASC-896) use available pip from the host

---

tasks/os_service_setup.yml

Previous merged commit (ac144e41e0dae33d93586c91ef1ce561ceb66e0b) uses available pip on the host (infra1), it was able to resolve bug ASC-896, however, when looking into the logs there are several places showing that the available pip on the host is very old (8.1.1).
This PR is trying to solve the old pip by not using the available pip on host, instead it will download and install new pip from pypa

(ASC-896) install correct pip on SUT when test with RPC-O master

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py
molecule/default/tests/test_write_to_attached_storage.py

This reverts commit c1b505d65776a94afb6263ba6998d376498180b5.
The upstream cause of this issue is believed to be fixed. So, these
tests should no longer be skipped.

Revert "ASC-883 Skip SSH tests until ASC-883 is resolved"

---

tasks/maas_setup.yml

Prior to this PR, rpc-maas repo is not cloned during RCP-O deployment.
This PR is to clone the repo for rpc-maas test.

(ASC-922) cloning rpc-maas repo

---

tasks/maas_setup.yml

Prior to this PR, ansible tasks failed at task "Check metadata variables are defined" in https://github.com/rcbops/rpc-maas/blob/master/playbooks/maas-pre-flight.yml because `rpc_env_identifier` is set to be `unknown` in https://github.com/rcbops/rpc-maas/blob/master/playbooks/templates/common/macros.jinja
This PR is to skip the mass_pre_flight_metadata by setting maas_pre_flight_metadata_check_enabled to be false.

(ASC-922) set maas_pre_flight_metadata_check_enabled to false

---

tasks/maas_setup.yml

Prior to this PR, maas_rabbitmq_password variable is not defined on CI, so it fails to run the maas-infra-rabbitmq.yml playbook that creates a user within the rabbitmq cluster for the purposes of monitoring.
This PR is to set the maas_rabbitmp_password to be a default value as defined in https://github.com/rcbops/rpc-maas/blob/7e1bde1df338cb60fcfd810b43ed3c8640670311/doc/source/usage.rst

(ASC-922) set maas_rabbitmq_password for maas setup

---

tasks/maas_setup.yml

The credentials in rpc-maas/tests/user_rpcm_secrets.yml file is needed while executing maas site.yml playbook.
Cconcatnating the first yml file onto the second yml file creates some format errors when executing site.yml ansible playbook.
This PR is to remove the lines starting with '---', '#', or an empty line of the rpc-maas user_rpcm_secrets.yml before adding the credentials to user_secrets.yml

(ASC-922) concat rpc-maas rpcm secret file to rpco user_secrets yml file

---

tasks/main.yml
tasks/ssh_key_containers.yml
vars/main.yml

This commit adds a task to ensure that the ssh key for root on localhost
is added to the infrastructure containers. Prior to this commit, running
the molecule converge step failed when the MNAIO environment was
deployed from pre-existing images. This is because the deploy hosts key
is propagated to the VMs in the environment but not the containers.

ASC-1035 Ensure authorized key on containers

---

molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_hypervisor_free.py
molecule/default/tests/test_rpc_version.py

This commit changes the lookup mechanism for the rpc_product_release
value from an environment variable to an ansible fact. In CI, the
environment variable falls out of scope prior to the execution of the
test. Since the ansible fact is defined, it becomes a more reliable
source for this value.

    ASC-1043 Use ansible fact for rpc_product_release

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py
molecule/default/tests/test_write_to_attached_storage.py

The two tests that were previously failing due the lack of being able to
SSH into the SUT have triggered failures via the xfail tag. This means
that the tests unexpectedly passed indicating that the issue has been
resolved. This commit removes these tags so that the tests will resume
there normal behavior.

RI-417 Remove xfail tags

---

tasks/delete_existing_networks.yml
tasks/main.yml
tasks/os_service_setup.yml
tasks/set_facts.yml
tasks/support_key.yml

When testing on MNAIO images previously deployed, there can be existing
openstack network resources that prevent the openstack-service-setup
from being able to deploy its expected network topology.
This commit adds a set of tasks to delete any existing openstack network
resources prior to executing the openstack-service-setup.

 ASC-1044 Add delete networks task

---

tasks/delete_existing_security_groups.yml
tasks/main.yml

When testing on MNAIO images previously deployed, there can be existing
openstack security group resources that prevent the
openstack-service-setup from being able to deploy its expected security
groups. This failure also prevents the playbook advancing to the image
creation task.
This commit adds a set of tasks to delete any existing openstack
security group resources prior to executing the openstack-service-setup.

ASC-1049 Add delete security groups task

---

tasks/maas_setup.yml

Prior to this PR, ansible task of 'Run maas-verify-local' in maas-setup.yml is running too long and went over the ssh timeout.
This PR to add async to the task to fix the timeout issue

(ASC-901) Added async to fix the timout issue

---

tasks/main.yml

Currently, the maas setup assumes that the maas variables file is
located at
`/opt/rpc-openstack/etc/openstack_deploy/user_rpco_maas_variables.yml`
which is not the case on newton. This commit sets the inclusion of the
maas setup playbook to be skipped on newton.

ASC-1053 Skip maas setup on newton

---

tasks/maas_setup.yml

Prior to this PR, verify task was set to run up to 30 minutes, unfortunately, it does not have enough time to complete the task.
This PR to increase both setup and verify tasks, also put a debug 'date' before and after the tasks to see how long they actually ran.

(maint) increase running time for maas setup and verify tasks

---

tasks/main.yml

Prior to this PR, maas setup and verify takes a long time to complete, it also fails at several places. Those behavior prevent the quick turn around defect fixing and test developing cycles.
This PR to remove maas setup and verify from all production branches

(Maint) remove maas setup and verify from production

---

tasks/main.yml

Reverts rcbops/molecule-rpc-openstack-post-deploy#96 to get maas setup and verify tasks back to 'dev' branch

Revert "(Maint) remove maas setup and verify from production"

---

molecule/default/tests/test_cinder_attach.py
molecule/default/tests/test_cinder_lvm.py
molecule/default/tests/test_cinder_service.py
molecule/default/tests/test_cinder_volume.py
molecule/default/tests/test_create_and_assign_floating_ip.py
molecule/default/tests/test_create_bootable_volume.py
molecule/default/tests/test_create_instance_from_bootable_volume.py
molecule/default/tests/test_create_snapshot_on_instance.py
molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_env_scan.py
molecule/default/tests/test_instance_per_network_per_hypervisor.py
molecule/default/tests/test_rpc_version.py
molecule/default/tests/test_scan_images_and_flavors.py
molecule/default/tests/test_swift_dispersion.py
molecule/default/tests/test_swift_recon_md5.py
molecule/default/tests/test_swift_recon_unmount.py
molecule/default/tests/test_swift_ring_data_balance.py
molecule/default/tests/test_swift_stat.py
molecule/default/tests/test_verify_configured_quotas.py
molecule/default/tests/test_verify_disabled_nova_force_config_drive.py
molecule/default/tests/test_verify_galera_cluster_after_reboot.py
molecule/default/tests/test_verify_mbu_installed.py
molecule/default/tests/test_verify_networks_created.py
molecule/default/tests/test_verify_one_rabbitmp_channel_per_connection.py
molecule/default/tests/test_verify_users_and_tenants.py
molecule/default/tests/test_write_to_attached_storage.py

This commit replaces the use of the legacy `os-infra_hosts` node group
with the `shared-infra_hosts` group.

ASC-1100 Use shared-infra_hosts

---

tasks/server_setup.yml

System tests failed many tests in which a server needs to be created. During the server creation, the server status was seen to change from "Build" to "ERROR". It is unsure that there is at least one server has been successfully created, including the test_server created in server_setup.yml
This PR to add a step of checking if the server created in server_setup.yml is successful.

(ASC-1140) Added checking server creating status

---

tasks/delete_existing_networks.yml

Pike is currently failing when attempting to delete the subnets on all
existing routers during the converge step.  This is caused by the
"router show" information for the router not containing the key
"interfaces_info", which causes the condition to prematurely fail due
to the undefined variable used in the template.
This commit updates the code to query for the ports associated with the
routers. The "subnet_id" values associated with these ports are used
rather than the "interfaces_info" value. The router ids and there
subnets are mapped together in order to simplify the variables used for
the removal of the routers and their underlying components.

ASC-1052 Fix remove router subnet

---

molecule/default/tests/test_hypervisor_free.py

This commit fixes an error in connecting to the `nova_conductor` host.
The host is now determined by introspecting the intersection of hosts in
the `nova_conductor` group that are also in the `infraX-host_containers`
group for the infraX target host.

ASC-1204 Fix test_get_nova_allocation_ratios

---

tasks/enable_api_access.yml
tasks/volume_setup.yml

It is not guaranteed that the 'infra1' host will have the prerequisites
satisfied in order to use the OpenStack Ansible connection plug-in.
Therefore, delegate said commands to localhost where there is tighter
control over the Python environment.

ASC-1180 Delegate OpenStack Ansible Connection Commands to Localhost

---

molecule/default/tests/test_create_bootable_volume.py

Prior to this PR, teardown in test_create_bootable_volume is handled in test level.
This causes the problem of deleting not-ready-for-deleting volume and cause the test failed.
This PR to remove the teardown and using openstack_properties fixture in conftest.py

(ASC-1246) removed teardown in test level

---

molecule/default/tests/conftest.py

Add a fixture for getting an authenticated connection to OpenStack from the
'openstacksdk' Python API module. Also, I fixed up some formatting in the file
as well.

ASC-1082 Add OpenStack API Connection Fixture

---

molecule/default/tests/conftest.py

Add the "os_api_conn" fixture back after reverting #134. This time without
including the "glance_nfs_share_path" or "glance_nfs_share_path" variables.
~~This is blocked by #134 and needs to rebased before merge.~~

ASC-1082 Add Back OS API Conn Support

---

molecule/default/tests/test_instance_per_network_per_hypervisor.py
molecule/default/tests/test_write_to_attached_storage.py

Commit 1: 812a2883cfa6e2997883d3e895a897d41f911f77
Prior to this commit, variable 'ssh_attempt' was assigned inside a try-except-else
block, and the block is inside a 'for' loop. It is my understanding that if
the variable is not 'global' then the assignment alwasy go into the innermost
scope.
The test passed in local mnaio but failed on CI, that could be the reason that
depending on the python versions, the current varriable assignment might or
might not be accepted when the variable is assigned deeply inside a block
which is inside a 'for' loop.
The commit 1 (812a2883cfa6e2997883d3e895a897d41f911f77) is simply declaring the variable before enter the 'for' loop. If it still fail the next round of CI, then 'global' must be used since 'nonlocal' is only support in python 3.x and later …

Asc 1268 fix attached storage and hypervisor tests

---

tasks/server_setup.yml

Given the sporadic performance of our CI system, the timeout waiting for a
server instance to spawn should be increased to 10 minutes.

ASC-1222 Increase Timeout for Server Setup Converge Task

---

tasks/support_key.yml

The 'rpc_support.pub' public key is not present on the deployment host which
causes the 'support_key.yml' to fail. Instead of writing the file to the
depoyment host the task was update to read the 'rpc_support.pub' key from
an existing variable.

ASC-1342 Fix Missing Support Public Key Issue

---

tasks/os_service_setup.yml

The "deactivate" command would always succeed which would report that the
"Run openstack-service-setup" would always succeed regardless of what
actually happened.

ASC-1367 Fix "os_service_setup" Failure to Fail

---

molecule/default/tests/test_dhcp_agents.py
molecule/default/tests/test_rpc_version.py
molecule/default/tests/utils.py

Looking up for rpc_product_release has been changed recently in
commit 46760db71ee69387866a3cd0aa649ebb857630c3. The old way of
getting 'epc_product_release' is no longer working so it will
break other system tests (test_dhcp_agents.py and test_swift_stat.py).
This PR to relocate the method to utils.py file so other tests can
utilize it. Related test cases are also modified in this PR

(ASC-1393) reuse gen_dict_extract function

---

tasks/set_facts.yml

This commit adds the '-L' flag to the find command for looking up the
inventory file for osp-mnaio.  Previous to this commit, if the repo was
cloned to a location other than `/opt` the find command would be unable
to locate the file.

ASC-1388 Follow symlink when looking up inventory

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_and_assign_floating_ip.py
molecule/default/tests/test_create_bootable_volume.py
molecule/default/tests/test_create_instance_from_bootable_volume.py
molecule/default/tests/test_create_snapshot_from_instance.py
molecule/default/tests/test_instance_per_network_per_hypervisor.py
molecule/default/tests/test_write_to_attached_storage.py
tasks/flavor_setup.yml
tasks/network_setup.yml
tasks/server_setup.yml
tasks/volume_setup.yml
vars/main.yml

Update the "openstack_properties" fixture to automatically extract all the
variables from Ansible. Also, I update the naming of the Ansible variables
to be consistent. Let me know if the naming is confusing.

ASC-1253 Automatically Extract OpenStack Properties from Ansible

---

tasks/os_service_setup.yml

Increase the timeout to 45 minutes to allow for more time to download OS images
which can experience erratic performance when downloading. (Thanks internet!)

ASC-1397 Increase Timeout for "os_service_setup" Converge Task

---

molecule/default/tests/test_swift_stat.py

Currently the function run_on_container in pytest-rpc cannot be used
without providing the authentication to Openstack (done by running
`source /path/openrc).
This PR is a workaround for that issue until asc-1398 is fixed.

(ASC-1365) Workaround for asc-1398

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_and_assign_floating_ip.py
molecule/default/tests/test_create_bootable_volume.py
molecule/default/tests/test_create_instance_from_bootable_volume.py
molecule/default/tests/test_create_snapshot_from_instance.py
molecule/default/tests/test_instance_per_network_per_hypervisor.py
molecule/default/tests/test_write_to_attached_storage.py
tasks/flavor_setup.yml
tasks/network_setup.yml
tasks/server_setup.yml
tasks/volume_setup.yml
vars/main.yml

Reverts rcbops/molecule-rpc-openstack-post-deploy#157

Revert "ASC-1253 Automatically Extract OpenStack Properties from Ansible"

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_snapshot_from_instance.py

This is a pretty hefty change so if you want to do a live review on Zoom I'm fine with that.
Introduced new fixtures for creating server instances via the OpenStack API.
Tech debt:
The 'openstack_properties' fixture was also changed to detach it from the
Ansible variables file. This was necessary because the moment a fixture pulls
in the testinfra 'host' fixture it will attempt to run all tests against every
host regardless if the test uses the 'host' fixture or not.
I also duplicated information inside the 'openstack_properties' fixture because
I'm planning on changing the naming conventions of the dictionary when all tests
have been refactored to utilize the OpenStack API.

ASC-1314 Refactor 'test_create_snapshot_from_instance'

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_and_assign_floating_ip.py
molecule/default/tests/test_create_snapshot_from_instance.py

**conftest**
Updated the 'create_server' factory in 'conftest' to allow for specifying
'auto_ip' upon server creation. Discovered a better way to validate the
properties after server creation. Added a beginning sleep because OpenStack
lies about waiting until something is actually done.
Updated 'expect_os_property' to provide more detailed information if a property
was not found on the given OpenStack object.
Added a 'ping' helper with retry support.
**test_create_and_assign_floating_ip**
Added a beginning clean-up step for removing unattached floating IPs because it
was the easiest way to guarantee that the floating IP pool is not exhausted.

ASC-1311 Refactor 'test_create_and_assign_floating_ip'

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_and_assign_floating_ip.py
molecule/default/tests/test_create_instance_from_bootable_volume.py
molecule/default/tests/test_create_snapshot_from_instance.py

Created a new 'create_volume' dynamic fixture for generating volumes.
I updated the 'create_server' fixture to allow for bootable volume. Also, I
dropped the 'name' required argument for 'create_server' as it was just noise
to keep typing given we don't care about the name at all.
~Blocked by #168~

ASC-1313 Refactor 'test_create_instance_from_bootable_volume'

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_and_assign_floating_ip.py
molecule/default/tests/test_create_instance_from_bootable_volume.py

After doing some thinking about the fixtures I realized that I was typing way
too much extra code. I refactored the 'create_server' fixture to assign the
floating IP to an accessible property on the object. (See ASC-1416 for details
on the bug I found)
~Blocked by #169~

ASC-1313 Maintenance on Refactored Code

---

molecule/default/tests/conftest.py
molecule/default/tests/test_create_bootable_volume.py
molecule/default/tests/test_create_instance_from_bootable_volume.py

The test is pretty straightforward and utilzies fixtures that are already
available. I did fix a bug in the 'create_volume' fixture dealing with
naming newly created volumes. Also, I updated incorrect documentation I
ran into while copying and pasting from
'test_create_instance_from_bootable_volume.py'.

ASC-1341 Refactor 'test_create_bootable_volume'

---

tasks/osp_osa_ops.yml
vars/main.yml

OSP 13 deploys are currently not supporting `vxlan` network types.  The
`geneve` type appear to be the current default and supposedly supports all
of the functionality of `vxlan`.
This commit modifies the network type used by the openstack-ansible-ops
mnaio network creation script by dynamically replacing the `vxlan` value
for the `network_type` variable with the value of `geneve`.

ASC-1396 Use geneve network type not vxlan

---

molecule/default/tests/test_verify_one_rabbitmp_channel_per_connection.py

This commit fixes a condition where the `attach_rabbitmq_container`
variable could go undefined by the try logic that defines it.

ASC-1396 Fix undefined var in rabbitmq test

---

molecule/default/tests/test_hypervisor_free.py

This commit pulls the allocation ratios from the `nova.conf` file on the
director for validating the compute usages. This is OSP specific.

ASC-1257 Get nova allocation ratios from director

---

molecule/default/tests/test_bridges.py

It was determined that logic and approach of the test was sound. However, the
test name 'test_for_dead_taps' looks to be copy pasta from a different module.
The test has been renamed to something more meaningful. Modifications to
styling and docstrings were made as well.

ASC-1176 Refactor 'test_bridges'

---

molecule/default/tests/test_hypervisor_free.py

Updated the test to use the API as well as grab the 'nova.conf' from the
'nova_compute' host group instead of the 'nova_conductor'.

ASC-1318 Refactor 'test_hypervisor_free'

---

molecule/default/tests/test_env_scan.py

Updated test case accordingly to the fact that user 'keystone' is
deprecated from Stein and later releases.

(ASC-1424) Remove user 'keystone' for test against Stein and later

---

molecule/default/tests/test_rpc_version.py

Updated the test to utilize the updated 'openstack_properties' fixture which
includes OpenStack version information. Moved helpers from 'pytest-rpc' and
'utils.py' to this module given the narrow focus of said helpers. Updated
related tickets to indicate the change in location for the given helpers.

ASC-1321 Refactor 'test_rpc_version'

---

molecule/default/tests/conftest.py
molecule/default/tests/test_instance_per_network_per_hypervisor.py

Rewrote the test to utilize the API when possible and re-organized the code
to be more readable.
I cannot get the test to pass in my environments and I'm all out of ideas on why. Output below showing failure:
```bash
cmd = ("ip netns exec qdhcp-{} {} "
"ping -c1 -w2 8.8.8.8").format(network_id, ssh)
>               assert neutron_cmd(cmd).rc == 0
E               assert 255 == 0
E                +  where 255 = CommandResult(command="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/...rmission denied, please try again.\r\nPermission denied (publickey,password).").rc
E                +    where CommandResult(command="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/...rmission denied, please try again.\r\nPermission denied (publickey,password).") = <function _factory at …
```

ASC-1319 Refactor 'test_instance_per_network_per_hypervisor'

---

molecule/default/tests/conftest.py

The "configparser" backport library isn't playing nice with Rocky Bionic.
Updated the import to attempt to load the old school "ConfigParser" built-in
first for Python 2.7 compatibility.

ASC-1543 Fix "configparser" Backport Issue

---

tasks/os_version_file.yml
vars/main.yml

Turns out that the CI scripts will lay down a copy of '/etc/openstack-release'
if it doesn't exist somewhere in the post process. However, it already exists
then it assumes that the file is readable. Adding the '[default]' INI section
to the file makes it fail to import which in turn causes the post script to
fail with the result of no qTest results being published.
So, the modified file is now being appended with the extension of '.ini' to
differentiate it from the original file.

ASC-1559 Update "os_version_file" Task

---

molecule/default/tests/test_rpc_version.py

The "test_rpc_version" test module has a helper that did not properly identify
the "master" branch of RPC-O. I updated the helper to provide the fail safe
of codename "master" and version of "99" if the branch could not be determined.

ASC-1601 Fix "master" Branch Version Mismatch

---

molecule/default/tests/test_cinder_service.py
molecule/default/tests/test_list_cinder_volume_group_lxc.py
molecule/default/tests/test_verify_galera_cluster.py

Make sure that "shared-infra_hosts" is used as the hosts group when attempting
to access any of the "infra*" hosts.

ASC-1535 Standardize "testinfra" Hosts Group

---

molecule/default/tests/test_rpc_version.py

So it turns out that the '/etc/openstack-release' file on master branch does in
fact contain the correct codename! Given the weird nature of that file I think
it's best we just conditionally skip when on the 'master' branch.

ASC-1601 Conditionally Skip Version Check Test

---

requirements.yml
tasks/main.yml

The "server_delete" task file should be after the role import for
"ansible-role-pytest-rpc" because the aforementioned task needs to have the
"clouds.yaml" file be moved to the deployment host before executing.

ASC-1620 Fix Task Order

---

molecule/default/tests/test_write_to_attached_storage.py

This commit fixes errors in previously refactoring the commands in the
`write_to_attached_storage` test.  These commands were left with an
extraneous element in string fed to the format command which exceeded the
arguments given.  An error in the retry range for ssh connections has
also been corrected.

ASC-1264 Fix command argument out of range

---

molecule/default/tests/test_cinder_lvm.py

Prior to this PR, volumes are not created (due to the recent changes
in converge steps) and volume snapshot is not created for the test.
This PR adds volume and volume snapshot creation so that the test
can really test the cinder lvm volumes and volume snapshots.

(ASC-1503) update test for validating volume snapshots
