- molecule/default/playbook.yml
- molecule/default/tests/test_env_scan.py
This commit adds a test to scan for default OpenStack infrastructure
values.
> ASC-157 Add basic scan test

- .travis.yml
- molecule/default/tests/test_bridges.py
- molecule/default/tests/test_dhcp_agents.py
- molecule/default/tests/test_env_scan.py
- molecule/default/tests/test_for_acs-150.py
- molecule/default/tests/test_for_acs-295.py
- molecule/default/tests/test_hypervisor_free.py
- molecule/default/tests/test_mysql_replication.py
- requirements.txt
This commit adds flake8 lint testing to Travis CI for this repository.
> ASC-393 Add Travis lint testing

- molecule/default/tests/test_bridges.py
- molecule/default/tests/test_dead_taps.py
- molecule/default/tests/test_dhcp_agents.py
- molecule/default/tests/test_env_scan.py
- molecule/default/tests/test_for_acs-150.py
- molecule/default/tests/test_for_acs-295.py
- molecule/default/tests/test_hypervisor_free.py
- molecule/default/tests/test_mysql_replication.py
This commit adds UUID marks to the current tests in order for them to be
tracked by the test case management system.
> ASC-401 Add UUID values to tests

- molecule/default/tests/test_env_scan.py
- molecule/default/tests/test_hypervisor_free.py
This commit sets tests that are currently failing in MNAIO deploy
jobs with the specific reason for each.
> ASC-157 Skip failing tests

- molecule/default/tests/test_write_to_attached_storage.py
- molecule/default/vars/main.yml
- tasks/flavor_setup.yml
- tasks/image_setup.yml
- tasks/main.yml
- tasks/server_setup.yml
- tasks/volume_setup.yml
- vars/main.yml
This commit adds a test to attach a volume to an instance, create a
partition and filesystem on that volume, and verify you can write to it.
> ASC-257 Add write to attached volume test

- tasks/server_delete.yml
This commit fixes a bad ansible conditional statement in the
`server_delete` task.
> ASC-241 Fix ansible condition for server delete

- molecule/default/tests/test_dhcp_agents.py
This commit updates the `test_dhcp_agents.py:test_openvswitch` test to
accommodate for OpenStack versions newton and older. Older versions of
`openstack` cli do not have the `--network` flag for the `openstack
network agent list` command. So, for these versions the legacy `neutron`
cli is used to list the agents associated with each network.
> ASC-791 Add network agents logic for newton

- constraints.txt
- molecule/default/tests/test_swift_dispersion.py
- molecule/default/tests/test_swift_recon_md5.py
- molecule/default/tests/test_swift_recon_unmount.py
- molecule/default/tests/test_swift_ring_data_balance.py
- molecule/default/tests/test_swift_stat.py
This commit updates the swift tests to use the helpers from pytest-rpc.
> ASC-807 Use pytest-rpc swift helpers

- tasks/maas_setup.yml
- tasks/main.yml
This PR is to deploy maas on rpc-o
> (ASC-922) Run playbook to install and config MaaS

- molecule/default/tests/test_instance_per_network_per_hypervisor.py
- molecule/default/tests/test_write_to_attached_storage.py
Will revert the tests back when RI-417 is fixed
> (ASC-789) (ASC-883) (RI-417) xfail the tests until RI-417 is fixed

- tasks/maas_setup.yml
Reverts rcbops/molecule-rpc-openstack-post-deploy#86
> Revert "(ASC-897) (ASC-898) (ASC-899) Run maas-verify.yml --tags "maas-verify…"

- molecule/default/tests/glance_helpers.py
- molecule/default/tests/test_cinder_attach.py
- molecule/default/tests/test_cinder_lvm.py
- molecule/default/tests/test_cinder_service.py
- molecule/default/tests/test_cinder_volume.py
- molecule/default/tests/test_create_and_assign_floating_ip.py
- molecule/default/tests/test_create_bootable_volume.py
- molecule/default/tests/test_create_instance_from_bootable_volume.py
- molecule/default/tests/test_create_snapshot_on_instance.py
- molecule/default/tests/test_list_cinder_volume_group_lxc.py
- molecule/default/tests/test_scan_images_and_flavors.py
- molecule/default/tests/test_verify_configured_quotas.py
- molecule/default/tests/test_verify_disabled_nova_force_config_drive.py
- molecule/default/tests/test_verify_galera_cluster_after_reboot.py
- molecule/default/tests/test_verify_mbu_installed.py
- molecule/default/tests/test_verify_networks_created.py
- molecule/default/tests/test_verify_one_rabbitmp_channel_per_connection.py
- molecule/default/tests/test_verify_users_and_tenants.py
I have done my best to merge the tests and histories from the other molecules into this molecule. The history is *a little* funky, but still intact. We can zoom it out if you have questions on my methodology.
> ASC-1032 Merge Molecules into this Repo

- .flake8
- .travis.yml
- molecule/default/tests/test_hypervisor_free.py
- molecule/default/tests/test_list_cinder_volume_group_lxc.py
- molecule/default/tests/test_verify_disabled_nova_force_config_drive.py
Ref: https://github.com/rcbops/molecule-rpc-openstack-post-deploy/pull/103
> MAINT - Cherry-pick flake8 updates

- tasks/enable_api_access.yml
Add 'shade' Python package to the 'infra1' host.
> ASC-1180 (MAINT) Ensure 'shade' Installed on Infra1 Host

- tasks/delete_existing_networks.yml
Reverts rcbops/molecule-rpc-openstack-post-deploy#112
> Revert "ASC-1052 Fix remove router subnet"

- tasks/delete_existing_networks.yml
This PR cherry-picks the changes committed to dev to address the router subnet removal failures seen in the CI system-test pike job.
> ASC-1052 Cherry-pick router subnet removal fix

- tasks/volume_setup.yml
Revert the commit since it is breaking the Molecule converge step.
> Revert "ASC-1180 Refactor 'volume_setup' Task"

- tasks/volume_setup.yml
I cannot reproduce the timeout failure locally, so let's try increasing the
timeout to 10 minutes.
> ASC-1180 Increase 'volume_setup' Task Timeout

- molecule/default/requirements.yml
- molecule/default/tests/test_glance_nfs_backend.py
- tasks/main.yml
- tasks/set_facts.yml
- tasks/setup_nfs_server.yml
- vars/main.yml
This test verifies that a OpenStack administrator can change the backend of
Glance to NFS.
Blocked by #131
> ASC-1082 Add Test for Glance NFS Backend

- molecule/default/tests/test_rpc_version.py
This commit adds a method to perform a recursive search for a given key
in a given dictionary.  This method is then used to find the value of
the `rpc_product_release` ansible fact without needing to know where
this key is located in the fact data structure.
This solution was pulled from [stack overflow](https://stackoverflow.com/a/29652561)
> ASC-1340 Harden lookup of rpc_product_release

- tasks/network_setup.yml
- tasks/os_service_setup.yml
Update the 'delete_existing_networks.yml' and 'network_setup.yml' to utilize
the OSA connection plug-in.
This PR is a redo of #139.
> ASC-1221 Refactor Network Setup Converge Tasks

- tasks/server_delete.yml
- tasks/server_setup.yml
Update the 'server_delete.yml' and 'server_setup.yml' to utilize the OSA
connection plug-in.
> ASC-1222 Refactor Server Setup Converge Tasks

- tasks/flavor_setup.yml
Update the 'flavor_setup.yml' to utilize the OSA connection plug-in.
> ASC-1219 Refactor Flavor Setup Converge Task

- tasks/support_key.yml
Update the 'support_key.yml' to utilize the OSA connection plug-in.
> ASC-1342 Refactor Support Key Converge Task

- tasks/support_key.yml
A task directive was not correctly indented. FIXED!
> ASC-1342 Fix YAML Formatting Mistake

- molecule/default/tests/test_swift_stat.py
Prior to this PR, test_swift_stat.py is skipped (xFail) on Rocky
onward.
This PR to allow the test run on Rocky.
> (ASC-1365) Execute swift client on util container

- tasks/set_facts.yml
Utilize Ansible's built-in JSON filter to properly write the custom fact file
so that an automation engineer can run the full Molecule test suite repeatedly
without failure.
> ASC-1400 Write Custom Fact Correctly

- molecule/default/tests/test_scan_images_and_flavors.py
Update one suite of tests to utilized the OpenStack API for validation in order
to prove it works in a simple case.
> ASC-1060 Utilize OpenStack API for Validation

- molecule/default/tests/conftest.py
Turns out that attaching a floating IP is very difficult for OpenStack.
I increased the timeout to a ridiculous 10 minutes and moved the code for
attachment below verification that the server is running. The reason I think
failures occur only on the first attempt at creating a server with a floating
IP is because OpenStack uses aggressive caching.
> ASC-1341 Increase Floating IP Timeout

- molecule/default/tests/test_cinder_volume.py
This PR creates a non-bootable volume (different from other existing
test cases using openstackSDK to create bootable volume)
> (ASC-1310) Refactor "test_cinder_volume.py" Tests

- molecule/default/tests/test_dhcp_agents.py
Utilized the API to determine if a network has a running DHCP agent. I
spelunked the OpenStack CLI codebase and determined that the "agent"
sub-command is really just calling into parts of the "network" proxy on the
"openstack" SDK.
Not sure if this will work on Newton, but I'll run it on staging with Newton first.
> ASC-1316 Refactor 'test_dhcp_agents'

- molecule/default/tests/test_dead_taps.py
It was determined that logic and approach of the test was sound. The only
modifications made were to update styling and docstrings.
> ASC-1315 Refactor 'test_dead_taps'

- molecule/default/tests/test_cinder_service.py
Updated test to use openstacksdk
> (ASC-1309) Refactor "test_cinder_service.py" test

- molecule/default/tests/test_verify_mbu_installed.py
The test logic is sound so the only changes have to do with implementing
better code styling and docstrings. Ironically the test is now longer than
it was previously!
> ASC-1331 Refactor 'test_verify_mbu_installed'

- molecule/default/tests/test_cinder_lvm.py
Refactoring test using OpenStack Python API as much as possible.
> (ASC-1308) refactor "test_cinder_lvm.py" test

- molecule/default/tests/conftest.py
- molecule/default/tests/test_verify_networks_created.py
Updated the test to utilize the OpenStack Python API for validation.
> ASC-1332 Refactor 'test_verify_networks_created'

- molecule/default/tests/test_verify_configured_quotas.py
I did a rewrite of these tests to utilize test steps given the repeated
operations. I tossed the old test IDs and test names and introduced new ones.
> ASC-1328 Refactor 'test_verify_configured_quotas'

- molecule/default/tests/test_cinder_attach.py
Refacter system tests using OpenStack API
> (ASC-1307) refactor "test_cinder_attach.py"

- molecule/default/tests/test_swift_dispersion.py
The test logic is sound so no fundamentals were changed. Updates are only
to styling and docstrings.
> ASC-1323 Refactor 'test_swift_dispersion'

- molecule/default/tests/test_swift_recon_unmount.py
Test logic was sound so no fundamental changes were made. Only styling and
docstrings were updated.
> ASC-1325 Refactor 'test_swift_recon_unmount'

- molecule/default/tests/test_swift_recon_md5.py
Test logic was sound so no fundamental changes were made. Only styling and
docstrings were updated.
> ASC-1324 Refactor 'test_swift_recon_md5'

- molecule/default/tests/test_swift_ring_data_balance.py
Test logic was sound so no fundamental changes were made. Only styling and
docstrings were updated.
> ASC-1326 Refactor 'test_swift_ring_data_balance'

- molecule/default/tests/test_cinder_service.py
Prior to this PR, the existing test is only checking the cinder API V1 service
This PR will ensure to get the right cinder service to check
> (ASC-1536) Check the correct cinder service

- molecule/default/tests/test_list_cinder_volume_group_lxc.py
The test executing commands on cinder hosts, so this PR is only
to update the test file format.
> (ASC-1320) refactor test_list_cinder_volume_group_lxc.py test

- molecule/default/tests/test_verify_galera_cluster.py
The test is good, this PR is only updating the test file format
> (ASC-1330) refactor test_verify_galera_cluster.py test

- molecule/default/tests/test_verify_one_rabbitmp_channel_per_connection.py
Test is good, this PR only updates the test file format
> (ASC-1333) Refactor test_verify_one_rabbitmq_channel_per_connection test

- molecule/default/tests/test_create_and_assign_floating_ip.py
This commit alters the command to create the test server in the
`create_and_assign_floating_ip` test to ensure that the appropriate
security group is defined.  Without this setting, the root user on the
OSP director cannot ping the created server.
> ASC-1262 Use security group creating test server

- molecule/default/tests/test_cinder_lvm.py
Refactor test to use a snapshot fixture to guarantee teardown.
> ASC-1503 Use Snapshot Fixture
